swagger: '2.0'
info:
  title: NetVest backend
  version: '0.0.1'

schemes:
  - http
  - https

produces:
  - application/json

basePath: /api
paths:
  '/feed/latest':
    get:
      description: latest 10 Feed posts for current user
      parameters: []
      responses:
        200:
          description: user Feed
          schema:
            $ref: '#/definitions/Feed'
      tags:
      - feed

definitions:
  Feed:
    type: array
    items:
      $ref: '#/definitions/FeedItem'

  FeedItem:
    $ref: ./FeedItem.yaml

  Event:
    $ref: ./Event.yaml

  TradeEvent:
    $ref: ./TradeEvent.yaml

  WhatchlistEvent:
    $ref: ./WhatchlistEvent.yaml

  UpdateEvent:
    $ref: ./UpdateEvent.yaml

  Investor:
    $ref: ./Investor.yaml



  # note:
  # the more accurate term for this Type is "Security" (as a tradeable financial asset),
  # but for not to be mixed up with Informational Security
  # this is called Symbol
  Symbol:
    $ref: ./Symbol.yaml
