swagger: '2.0'
info:
  title: NetVest backend
  version: '0.0.0'

paths:
  '/api/feed/latest':
    get:
      description: latest 10 Feed posts for current user
      parameters: []
      responses:
        200:
          description: user Feed
          schema:
            type: object
            properties:
              id:
                type: number
