swagger: '2.0'
info:
  title: NetVest backend
  version: '0.0.0'

paths:
  '/api/feed/latest':
    get:
      description: latest 10 Feed posts for current user
      parameters: []
      responses:
        200:
          description: user Feed
          schema:
            $ref: '#/definitions/Feed'

definitions:
  Feed:
    type: array
    items:
      $ref: '#/definitions/FeedItem'

  FeedItem:
    $ref: ./FeedItem.yaml

  Investor:
    $ref: ./Investor.yaml

  FeedEvent:
    $ref: ./FeedEvent.yaml

  # note:
  # the more accurate term for this Type is "Security" (as a tradeable financial asset),
  # but for not to be mixed up with Informational Security
  # this is called Symbol
  Symbol:
    type: object
    properties:
      ticker:
        type: string
        description: Symbol ticker
      company:
        type: string
        description: company name corresponding to that symbol
