swagger: '2.0'
info:
  title: NetVest backend
  version: '0.1.0'

schemes:
  - http
  - https

consumes:
  - application/json
produces:
  - application/json

basePath: /api
paths:
  '/feed':
    $ref: ../api/feed/GetFeed.yaml

  '/feed/{feed_id}':
    $ref: ../api/feed/FeedById.yaml

  '/feed/{feed_id}/comments':
    $ref: ../api/feed/GetPostFeedComments.yaml

  '/auth/register':
    $ref: ../api/auth/Register.yaml

  '/auth/login':
    $ref: ../api/auth/Login.yaml

  '/auth/logout':
    $ref: ../api/auth/Logout.yaml

  '/auth/confirm-email':
    $ref: ../api/auth/ConfirmEmail.yaml

  '/auth/change-email':
    $ref: ../api/auth/ChangeEmail.yaml

  '/comments':
    $ref: ../api/comments/GetPostComments.yaml

definitions:
  # Put here only COMMON definitions

  Feed:
    $ref: ../api/feed/Feed.yaml

  FeedItem:
    $ref: ../api/feed/FeedItem.yaml

  Investor:
    $ref: ./Investor.yaml

  Symbol:
    $ref: ./Symbol.yaml

  Error:
    $ref: ./Error.yaml

  User:
    $ref: ./User.yaml

  Comments:
    $ref: ../api/comments/Comments.yaml
