swagger: '2.0'
info:
  title: NetVest backend
  version: '0.1.0'

schemes:
  - http
  - https

consumes:
  - application/json
produces:
  - application/json

basePath: /api
paths:
  '/feed':
    $ref: ../api/feed/swag/GetFeed.yaml

  '/feed/{feed_id}':
    $ref: ../api/feed/swag/FeedById.yaml

  '/feed/{feed_id}/comments':
    $ref: ../api/feed/swag/GetPostFeedComments.yaml

  '/auth/register':
    $ref: ../api/auth/swag/Register.yaml

  '/auth/login':
    $ref: ../api/auth/swag/Login.yaml

  '/auth/login/facebook':
    $ref: ../api/auth/swag/LoginFacebook.yaml

  '/auth/logout':
    $ref: ../api/auth/swag/Logout.yaml

  '/auth/confirm-email':
    $ref: ../api/auth/swag/ConfirmEmail.yaml

  '/auth/change-email':
    $ref: ../api/auth/swag/ChangeEmail.yaml

  '/admin':
    $ref: ../api/admin/swag/Intro.yaml

  '/comments':
    $ref: ../api/comments/swag/GetPostComments.yaml

  '/comments/count':
    $ref: ../api/comments/swag/GetCount.yaml

  '/comments/abuse':
    $ref: ../api/comments/swag/Abuse.yaml

  '/investors':
    $ref: ../api/investors/swag/GetInvestors.yaml

  '/investors/{investor_id}':
    $ref: ../api/investors/swag/GetInvestor.yaml

  '/static/pic/{hash}':
    $ref: ../api/statics/swag/GetPic.yaml

definitions:

  Feed:
    $ref: ../api/feed/swag/Feed.yaml

  FeedItem:
    $ref: ../api/feed/swag/FeedItem.yaml

  Investor:
    $ref: ../api/investors/swag/Investor.yaml

  Symbol:
    $ref: ./Symbol.yaml

  Error:
    $ref: ./Error.yaml

  User:
    $ref: ./User.yaml

  Comments:
    $ref: ../api/comments/swag/Comments.yaml

  CommentsItem:
    $ref: ../api/comments/swag/CommentItem.yaml

  CommentUser:
    $ref: ../api/comments/swag/CommentUser.yaml
