swagger: '2.0'
info:
  title: NetVest backend
  version: '0.0.2'

schemes:
  - http
  - https

consumes:
  - application/json
produces:
  - application/json

basePath: /api
paths:
  '/feed/latest':
    get:
      description: latest 10 Feed posts for current user
      parameters: []
      responses:
        200:
          description: user Feed
          schema:
            $ref: '#/definitions/Feed'
      tags:
      - feed

  '/auth/register':
    post:
      description: Creates new user of app [Netvest User](https://weezlabs.atlassian.net/wiki/display/NET/User+Roles+-+The+Netvest+User)
      parameters:
      - name: full_name
        in: formData
        required: true
        type: string
        description: Full Name of [Netvest User](https://weezlabs.atlassian.net/wiki/display/NET/User+Roles+-+The+Netvest+User)
      - name: email
        in: formData
        required: true
        type: string
        description: Email
      - name: password
        in: formData
        required: true
        type: string
        format: password
        description: Password
      responses:
        200:
          description: user model
          schema:
            $ref: '#/definitions/User'
        403:
          description: Errors of registration.
          schema:
            $ref: '#/definitions/Error'
      tags:
      - auth
  '/auth/login':
    post:
      description: Authenticates user by email and password
      parameters:
      - name: email
        in: formData
        required: true
        type: string
        description: Email
      - name: password
        in: formData
        required: true
        type: string
        format: password
        description: Password
      responses:
        200:
          description: user model
          schema:
            $ref: '#/definitions/User'
        403:
          description: Errors of authentication.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: User not exists
          schema:
            $ref: '#/definitions/Error'
      tags:
      - auth
  '/auth/logout':
    post:
      description: Logouts user
      parameters: []
      responses:
        200:
          description: logout successful
      tags:
      - auth

definitions:
  Feed:
    type: array
    items:
      $ref: '#/definitions/FeedItem'

  FeedItem:
    $ref: ../api/feed/FeedItem.yaml

  Event:
    $ref: ../api/feed/Event.yaml

  TradeEvent:
    $ref: ../api/feed/TradeEvent.yaml

  WatchlistEvent:
    $ref: ../api/feed/WatchlistEvent.yaml

  UpdateEvent:
    $ref: ../api/feed/UpdateEvent.yaml

  Investor:
    $ref: ./Investor.yaml

  Symbol:
    $ref: ./Symbol.yaml

  Error:
    $ref: ./Error.yaml

  User:
    $ref: ./User.yaml
