swagger: '2.0'
info:
  title: NetVest backend
  version: '0.1.0'

schemes:
  - http
  - https

consumes:
  - application/json
produces:
  - application/json

basePath: /api
paths:
  '/feed':
    get:
      description: latest 10 Feed posts for current user
      parameters: []
      responses:
        200:
          description: user's Feed
          schema:
            $ref: '#/definitions/Feed'
      tags:
      - feed

  '/auth/register':
    $ref: ../api/auth/Register.yaml

  '/auth/login':
    $ref: ../api/auth/Login.yaml

  '/auth/logout':
    $ref: ../api/auth/Logout.yaml

definitions:
  # Put here only COMMON definitions

  Feed:
    type: array
    items:
      $ref: '#/definitions/FeedItem'

  FeedItem:
    $ref: ../api/feed/FeedItem.yaml

  Investor:
    $ref: ./Investor.yaml

  Symbol:
    $ref: ./Symbol.yaml

  Error:
    $ref: ./Error.yaml

  User:
    $ref: ./User.yaml
