---
- hosts: all
  remote_user: root

  tasks:
  - name: ping
    ping:

  - name: ensure ubuntu user
    user:
      name: ubuntu

  - name: create env's dir `{{ netvest_env }}`
    file:
      path: '/home/ubuntu/netvest/{{ netvest_env }}'
      state: directory
